export const PATHS = {
	BASKET: '/basket',
	CHECKOUT: '/checkout',
	// FAIL_PAYMENT: '/fail-payment',
	HOME: '/',
	NOT_FOUND: '/not-found',
	PANEL_LOGIN: '/login',
	PANEL_ORDERS: '/panel-orders',
	PANEL_PRODUCT: '/panel-product',
	PANEL_QUANTITY: '/panel-quantity',
	PRODUCT: '/product',
	PRODUCTS: '/products',
	// SUCCESS_PAYMENT: '/success-payment',
	PAYMENT_RESULT: '/payment-result/:result',
}
